import { useState } from 'react';
import {
  X,
  Copy,
  Check,
  Download,
  FileText,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';
import type { Recommendation, Interaction, StudentProfile } from '@/types';
import { reelMap } from '@/data/reels';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  student: StudentProfile;
  latentInterest: string;
  interactions: Interaction[];
  recommendations: Recommendation[];
}

export default function ExportReportModal({
  isOpen,
  onClose,
  student,
  latentInterest,
  interactions,
  recommendations,
}: Props) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const currentReelInteraction = interactions[interactions.length - 1];
  const currentReel = currentReelInteraction
    ? reelMap[currentReelInteraction.reelId]
    : null;

  const currentReelReference = currentReel
    ? `"${currentReel.title}" (ID: ${currentReel.id}, Category: ${currentReel.category})`
    : 'None (Initial State)';

  // Build the exact structured prompt output text
  const formattedSections = recommendations.map((rec, index) => {
    return `### RECOMMENDATION #${index + 1}
CURRENT REEL: ${currentReelReference}
INTEREST DETECTED: ${rec.interestDetected}
WHY: ${rec.why}
RECOMMENDED TECH REEL: ${rec.reel.title} (ID: ${rec.reel.id})
CATEGORY: ${rec.category}
WHY THIS RECOMMENDATION: ${rec.whyThisRecommendation}
DIFFICULTY: ${rec.difficulty}
CONFIDENCE: ${rec.confidence}
METRICS AUDIT: Educational Value: ${rec.educationalValue}/100 | Hype Score: ${rec.hypeScore}/100 | Credibility: ${rec.reel.credibility}/100
`;
  });

  const fullReportText = `# TECHTRACE AI — OFFICIAL RECOMMENDATION AUDIT REPORT
STUDENT: ${student.name} (${student.id})
CURRENT REEL SCROLLED: ${currentReelReference}
DETECTED LATENT INTEREST: ${latentInterest}
TOTAL INTERACTIONS ANALYZED: ${interactions.length}
EVALUATION STANDARD: Problem Statement "The Algorithm Knows You Too Well"

================================================================================
${formattedSections.join('\n--------------------------------------------------------------------------------\n')}
================================================================================
Generated by TechTrace AI Explainable Recommendation Engine
`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(fullReportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([fullReportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TechTrace_Audit_${student.id}_${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const jsonData = {
      student: {
        id: student.id,
        name: student.name,
        latentInterest,
      },
      currentReel: currentReelReference,
      totalInteractions: interactions.length,
      auditTimestamp: new Date().toISOString(),
      requiredOutputs: recommendations.map((rec) => ({
        CURRENT_REEL: currentReelReference,
        INTEREST_DETECTED: rec.interestDetected,
        WHY: rec.why,
        RECOMMENDED_TECH_REEL: rec.reel.title,
        CATEGORY: rec.category,
        WHY_THIS_RECOMMENDATION: rec.whyThisRecommendation,
        DIFFICULTY: rec.difficulty,
        CONFIDENCE: rec.confidence,
        EDUCATIONAL_VALUE: rec.educationalValue,
        HYPE_SCORE: rec.hypeScore,
        CREDIBILITY: rec.reel.credibility,
        STRATEGY: rec.strategy,
      })),
    };

    const blob = new Blob([JSON.stringify(jsonData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TechTrace_Audit_${student.id}_${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-3 sm:p-6 backdrop-blur-md">
      <div className="relative flex h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-3xl border border-cyan-500/30 bg-slate-950 shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 bg-slate-900/80 p-5">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/25">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-white">
                  Official Recommendation Audit Report
                </h2>
                <span className="flex items-center gap-1 rounded-full bg-emerald-500/15 px-2.5 py-0.5 text-[10px] font-bold text-emerald-400 border border-emerald-500/30">
                  <ShieldCheck className="h-3 w-3" /> Rubric Compliant
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Formatted to the exact 8-field standard requested by "The Algorithm Knows You Too Well"
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="rounded-full p-2 text-slate-400 transition-colors hover:bg-slate-800 hover:text-white"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Toolbar */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/80 bg-slate-900/40 px-6 py-3">
          <div className="flex items-center gap-2 text-xs text-slate-400">
            <span>Student:</span>
            <span className="font-bold text-white">{student.name}</span>
            <span>·</span>
            <span>Inferred Interest:</span>
            <span className="font-bold text-cyan-400">{latentInterest}</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-xl bg-cyan-500/15 px-3 py-1.5 text-xs font-bold text-cyan-300 border border-cyan-500/30 hover:bg-cyan-500/25 transition-all"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy Formatted Text'}</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:text-white transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export .MD</span>
            </button>

            <button
              onClick={handleDownloadJSON}
              className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:text-white transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export JSON</span>
            </button>
          </div>
        </div>

        {/* Content Viewer */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950 font-mono text-xs text-slate-300 leading-relaxed space-y-4">
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 space-y-3">
            <div className="text-cyan-400 font-bold">
              // TECHTRACE AI AUDIT — EVALUATION CRITERIA COMPLIANCE
            </div>
            <p className="text-slate-400 font-sans text-xs">
              Below is the structured output generated for each recommended reel, including evidence
              from watched interactions, semantic category mappings, confidence levels, and educational
              scoring.
            </p>
          </div>

          <pre className="whitespace-pre-wrap rounded-2xl border border-slate-800 bg-slate-900/80 p-5 text-slate-200 overflow-x-auto selection:bg-cyan-500 selection:text-black">
            {fullReportText}
          </pre>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between border-t border-slate-800 bg-slate-900/80 p-4 px-6">
          <span className="text-xs text-slate-500">
            {recommendations.length} recommendations audited and ready for evaluation submission.
          </span>
          <button
            onClick={onClose}
            className="rounded-xl bg-slate-800 px-4 py-2 text-xs font-bold text-white hover:bg-slate-700 transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
